development:
  STRIPE_PUBLISHABLE_KEY: pk_test_5jJnBEWP58uma9eoJZsbahsq
  STRIPE_SECRET_KEY: sk_test_2gB1xh7jwrowOkemhCZrhR4N

test:
  STRIPE_PUBLISHABLE_KEY: pk_test_5jJnBEWP58uma9eoJZsbahsq
  STRIPE_SECRET_KEY: sk_test_2gB1xh7jwrowOkemhCZrhR4N

production:
  STRIPE_PUBLISHABLE_KEY: pk_live_pqlFH7V1YEcqpgas6VaQS22N
  STRIPE_SECRET_KEY: sk_live_eIhogsUoz2lS7KwmF87WhPEg
